eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

server:
  port: 8005

spring:
  application:
    name: api-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true
